//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DEV_CODES_APPDBEntities : DbContext
    {
        public DEV_CODES_APPDBEntities()
            : base("name=DEV_CODES_APPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<L_AdditionalFireSmokeFeatures> L_AdditionalFireSmokeFeatures { get; set; }
        public virtual DbSet<L_AsbestoesReason> L_AsbestoesReason { get; set; }
        public virtual DbSet<L_ConstructionType> L_ConstructionType { get; set; }
        public virtual DbSet<L_Country> L_Country { get; set; }
        public virtual DbSet<L_County> L_County { get; set; }
        public virtual DbSet<L_FireBarriers> L_FireBarriers { get; set; }
        public virtual DbSet<L_FirePartition> L_FirePartition { get; set; }
        public virtual DbSet<L_OccupancyTypes> L_OccupancyTypes { get; set; }
        public virtual DbSet<L_ScreenName> L_ScreenName { get; set; }
        public virtual DbSet<L_SpecialDetailedReq> L_SpecialDetailedReq { get; set; }
        public virtual DbSet<L_StakeHolderType> L_StakeHolderType { get; set; }
        public virtual DbSet<L_State> L_State { get; set; }
        public virtual DbSet<L_Suffix> L_Suffix { get; set; }
        public virtual DbSet<L_TransactionType> L_TransactionType { get; set; }
        public virtual DbSet<L_WasterWaterSupplyType> L_WasterWaterSupplyType { get; set; }
        public virtual DbSet<L_WaterSupplyType> L_WaterSupplyType { get; set; }
        public virtual DbSet<L_WorkType> L_WorkType { get; set; }
        public virtual DbSet<T_Address> T_Address { get; set; }
        public virtual DbSet<T_BuildingApplicationInformation> T_BuildingApplicationInformation { get; set; }
        public virtual DbSet<T_BuildingInformation> T_BuildingInformation { get; set; }
        public virtual DbSet<T_IndividualAdditionalInformation> T_IndividualAdditionalInformation { get; set; }
        public virtual DbSet<T_IndividualInformation> T_IndividualInformation { get; set; }
        public virtual DbSet<T_OrganizationInformation> T_OrganizationInformation { get; set; }
        public virtual DbSet<temp_BPMData> temp_BPMData { get; set; }
    
        public virtual ObjectResult<usp_getstackHolderInfo_Result> usp_getstackHolderInfo(string searchStr, string type)
        {
            var searchStrParameter = searchStr != null ?
                new ObjectParameter("SearchStr", searchStr) :
                new ObjectParameter("SearchStr", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getstackHolderInfo_Result>("usp_getstackHolderInfo", searchStrParameter, typeParameter);
        }
    }
}
