//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_OccupancyTypes
    {
        public string OccupancyType_ID { get; set; }
        public string OccupancyType_Description { get; set; }
        public string OccupancyType_Code { get; set; }
    }
}
