//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Address()
        {
            this.T_BuildingInformation = new HashSet<T_BuildingInformation>();
            this.T_IndividualInformation = new HashSet<T_IndividualInformation>();
            this.T_OrganizationInformation = new HashSet<T_OrganizationInformation>();
        }
    
        public string Address_ID { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string StateName { get; set; }
        public string CountyName { get; set; }
        public string CountryName { get; set; }
        public int ZIP { get; set; }
        public Nullable<int> ZIP4_Format { get; set; }
        public string County_ID { get; set; }
        public string State_ID { get; set; }
        public string Country_ID { get; set; }
    
        public virtual L_Country L_Country { get; set; }
        public virtual L_County L_County { get; set; }
        public virtual L_State L_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BuildingInformation> T_BuildingInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_IndividualInformation> T_IndividualInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OrganizationInformation> T_OrganizationInformation { get; set; }
    }
}
