//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingVariance
    {
        public string BV_ID { get; set; }
        public string BV_UniformCode { get; set; }
        public string BV_VarianceApplied { get; set; }
        public string BV_ReasonForNoVariance { get; set; }
        public string BV_PetitionNumberAvailable { get; set; }
        public string BV_PetitionNumber { get; set; }
        public string BV_VarianceApproved { get; set; }
        public string BV_PreviousVariance { get; set; }
        public string BLdgAppInfo_ID { get; set; }
    
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
    }
}
