//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BuildingInformation()
        {
            this.T_IndividualInformation = new HashSet<T_IndividualInformation>();
            this.T_OrganizationInformation = new HashSet<T_OrganizationInformation>();
        }
    
        public string BldgInfo_ID { get; set; }
        public string BldgInfo_Name { get; set; }
        public string ParcelTax_ID { get; set; }
        public string bldgAppInfo_ID { get; set; }
        public string Address_ID { get; set; }
    
        public virtual T_Address T_Address { get; set; }
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_IndividualInformation> T_IndividualInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OrganizationInformation> T_OrganizationInformation { get; set; }
    }
}
