//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingMiscellaneous
    {
        public string BM_ID { get; set; }
        public string BM_MiscSpcInspections { get; set; }
        public string BM_MiscSpcInspectionDDL { get; set; }
        public string BM_AsbestosSurvey { get; set; }
        public string BM_AsbestosSurveyReason { get; set; }
        public string BM_SubmissionOwnCodeReviews { get; set; }
        public string BLdgAppInfo_ID { get; set; }
    
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
    }
}
