//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingApplicationInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_BuildingApplicationInformation()
        {
            this.T_BuildingInformation = new HashSet<T_BuildingInformation>();
            this.T_IndividualInformation = new HashSet<T_IndividualInformation>();
            this.T_OrganizationInformation = new HashSet<T_OrganizationInformation>();
        }
    
        public string BldgAppInfo_ID { get; set; }
        public string BldgAppInfo_Type { get; set; }
        public string BldgAppInfo_EstimatedCost { get; set; }
        public string BldgAppInfo_Description { get; set; }
        public string BldgAppInfo_TypeOfWork { get; set; }
        public string BldgAppInfo_AdditionalInformation { get; set; }
        public string TransType_ID { get; set; }
        public string WorkType_ID { get; set; }
        public string PmtInfo_ID { get; set; }
    
        public virtual L_TransactionType L_TransactionType { get; set; }
        public virtual L_WorkType L_WorkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_BuildingInformation> T_BuildingInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_IndividualInformation> T_IndividualInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_OrganizationInformation> T_OrganizationInformation { get; set; }
    }
}
