//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingOccupancy_Height_Area
    {
        public string BOHA_ID { get; set; }
        public string BOHA_OccupancyType { get; set; }
        public string BOHA_ConstructionType { get; set; }
        public string BOHA_MixedUse { get; set; }
        public string BOHA_SprinklerSystem { get; set; }
        public Nullable<int> BOHA_HeightStories { get; set; }
        public string BOHA_HeightFeet { get; set; }
        public string BOHA_LargestFloorArea { get; set; }
        public string BOHA_TotalFloorArea { get; set; }
        public Nullable<int> BOHA_OriginalConstructionYear { get; set; }
        public string BOHA_MaterialAbandoned { get; set; }
        public string BOHA_MaterialAbondonedList { get; set; }
        public string BLdgAppInfo_ID { get; set; }
    
        public virtual L_ConstructionType L_ConstructionType { get; set; }
        public virtual L_OccupancyTypes L_OccupancyTypes { get; set; }
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
    }
}
