//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BuildingApplicationInspectionInformation
    {
        public string BldgAppInspInfo_ID { get; set; }
        public System.DateTime BldgAppInspInfo_InspectionDate { get; set; }
        public System.DateTime BldgAppInspInfo_ViolationDate { get; set; }
        public string ViolationType_ID { get; set; }
        public string InspectionType_ID { get; set; }
        public string PaymentType_ID { get; set; }
        public string SpecialInspectionsType_ID { get; set; }
        public string BLdgAppInfo_ID { get; set; }
    
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
    }
}
