//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CommentsInformation
    {
        public string Comment_ID { get; set; }
        public string Comment_ApplicantDescription { get; set; }
        public string Comment_ReviewerDescription { get; set; }
        public string Comment_ScreenName { get; set; }
        public string BLdgAppInfo_ID { get; set; }
    
        public virtual L_ScreenName L_ScreenName { get; set; }
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
    }
}
