//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IndividualAdditionalInformation
    {
        public string IndiAddInfo_ID { get; set; }
        public string IndiAddInfo_JobTitle { get; set; }
        public Nullable<int> IndiAddInfo_LicenseNumber { get; set; }
        public string IndiAddInfo_LicenseType { get; set; }
        public string IndiAddInfo_OwnerBehalf { get; set; }
        public string IndiAddInfo_ViewApplication { get; set; }
        public string IndiAddInfo_ModifyApplication { get; set; }
        public string IndiAddInfo_DirectCommunication { get; set; }
        public string IndiAddInfo_ScheduleInspection { get; set; }
        public string IndiAddInfo_InsuranceCoverage { get; set; }
        public string IndiInfo_ID { get; set; }
    
        public virtual T_IndividualInformation T_IndividualInformation { get; set; }
    }
}
