//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrganizationInformation
    {
        public string OrgInfo_ID { get; set; }
        public string OrgInfo_Name { get; set; }
        public string OrgInfo_Authority { get; set; }
        public string Address_ID { get; set; }
        public string StkHoldType_ID { get; set; }
        public string BldgInfo_ID { get; set; }
        public string BLdgAppInfo_ID { get; set; }
        public string BldgAppInfo_ContactPersonID { get; set; }
    
        public virtual T_Address T_Address { get; set; }
        public virtual T_BuildingApplicationInformation T_BuildingApplicationInformation { get; set; }
        public virtual T_BuildingInformation T_BuildingInformation { get; set; }
        public virtual T_IndividualInformation T_IndividualInformation { get; set; }
    }
}
