//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PayeeInformation
    {
        public string PayeeInfo_ID { get; set; }
        public string PayeeInfo_IndInfo { get; set; }
        public string PayeeInfo_PayeeBusinessName { get; set; }
        public string PayeeInfo_PaymentType { get; set; }
        public string PayeeInfo_CheckNumber { get; set; }
        public string PayeeInfo_CheckAmount { get; set; }
        public string PmtInfo_ID { get; set; }
    
        public virtual L_PaymentType L_PaymentType { get; set; }
        public virtual T_IndividualInformation T_IndividualInformation { get; set; }
        public virtual T_Payment T_Payment { get; set; }
    }
}
